from rest_framework import serializers
from .models import Task

class TaskSerializer(serializers.ModelSerializer):
    """
    Serializer for Task model that handles conversion between model instances and JSON representation.
    
    WHY THIS MATTERS:
    - Acts as the translator between Django models and JSON API format
    - Automatically handles data validation based on model field types
    - Provides built-in create() and update() methods for handling POST/PUT/PATCH requests
    - Ensures data integrity by validating incoming data before saving to database
    - Controls which fields are exposed in the API (security and data minimization)
    """
    class Meta:
        """
        Meta class that contains metadata options for the serializer.
        
        WHY THIS MATTERS:
        - Defines which model this serializer works with
        - Controls which fields are included in the API representation
        - Specifies which fields should be read-only (prevents client from modifying auto-generated fields)
        """
        model = Task  # The model that this serializer is based on
        fields = ['id', 'title', 'description', 'is_completed', 'created_at']  # Fields to include in the API
        read_only_fields = ['id', 'created_at']  # Fields that cannot be modified via API (auto-generated)
        # WHY READ-ONLY FIELDS MATTER:
        # - id: Primary key is auto-generated by database, shouldn't be changed by client
        # - created_at: Timestamp is set automatically on creation, prevents client tampering